services:
  - type: web
    name: nexus-pcm
    runtime: image
    repo: https://github.com/pedrohenriquemarques720-stack/Nexus-PCM
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.12
